---

- name: install firefox
  become: yes
  apt:
    name:
      - firefox
      - firefox-locale-ja

- name: install other packages
  become: yes
  apt:
    name:
      - caja
      - ghex
      - meld
