---
- name: install firefox
  become: yes
  apt:
    name:
      - firefox
      - firefox-locale-ja

- name: install caja
  block:
    - name: install caja
      become: yes
      apt:
        name:
          - caja

- name: install other packages
  become: yes
  apt:
    name:
      - ghex
      - meld
