[tool.poetry]
name = "test-linux-devenv"
version = "0.1.0"
description = ""
authors = ["Kamei Shogo <km45@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.7"
molecule = "^3.0.2"
docker = "^4.1.0"
parse = "^1.14.0"
semver = "^2.9.0"

[tool.poetry.dev-dependencies]
autopep8 = "^1.4.4"
pylint = "^2.4.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
