---

vscode_common_settings_file_path: /home/vagrant/.config/Code/User/settings.json

vscode_plugins:
  # ----------------------------------------------------------------------------
  # Common
  # ----------------------------------------------------------------------------
  - alefragnani.Bookmarks
  - MS-CEINTL.vscode-language-pack-ja
  - ms-vscode-remote.vscode-remote-extensionpack
  - shardulm94.trailing-spaces
  - streetsidesoftware.code-spell-checker
  - Tyriar.sort-lines
  - wmaurer.change-case
  - wraith13.wandbox-vscode
  #
  #
  # ----------------------------------------------------------------------------
  # Binary
  # ----------------------------------------------------------------------------
  - slevesque.vscode-hexdump
  #
  #
  # ----------------------------------------------------------------------------
  # C++
  # ----------------------------------------------------------------------------
  - ajshort.include-autocomplete
  - jomiller.rtags-client
  - mine.cpplint
  - ms-vscode.cpptools
  - twxs.cmake
  - xaver.clang-format
  #
  #
  # ----------------------------------------------------------------------------
  # CSV
  # ----------------------------------------------------------------------------
  - GrapeCity.gc-excelviewer
  - mechatroner.rainbow-csv
  #
  #
  # ----------------------------------------------------------------------------
  # Docker
  # ----------------------------------------------------------------------------
  - ms-azuretools.vscode-docker
  #
  #
  # ----------------------------------------------------------------------------
  # Git
  # ----------------------------------------------------------------------------
  - eamodio.gitlens
  #
  #
  # ----------------------------------------------------------------------------
  # Java
  # ----------------------------------------------------------------------------
  - redhat.java
  #
  #
  # ----------------------------------------------------------------------------
  # Markdown
  # ----------------------------------------------------------------------------
  - DavidAnson.vscode-markdownlint
  - goessner.mdmath
  - shuworks.vscode-table-formatter
  #
  #
  # ----------------------------------------------------------------------------
  # Protocol buffers
  # ----------------------------------------------------------------------------
  - zxh404.vscode-proto3
  #
  #
  # ----------------------------------------------------------------------------
  # Python
  # ----------------------------------------------------------------------------
  - ms-python.python
  #
  #
  # ----------------------------------------------------------------------------
  # Restructured text
  # ----------------------------------------------------------------------------
  - lextudio.restructuredtext
  #
  #
  # ----------------------------------------------------------------------------
  # Vagrant
  # ----------------------------------------------------------------------------
  - marcostazi.VS-code-vagrantfile
  #
  #
  # ----------------------------------------------------------------------------
  # Xml
  # ----------------------------------------------------------------------------
  - DotJoshJohnson.xml
  #
  #
  # ----------------------------------------------------------------------------
  # yUML
  # ----------------------------------------------------------------------------
  - JaimeOlivares.yuml
