---

- name: checkout git repository
  become: true
  git:
    repo: https://github.com/cquery-project/cquery.git
    dest: /usr/local/src/cquery-{{ cquery_version }}
    version: "v{{ cquery_version }}"

- name: install requirements
  become: true
  apt:
    name: libc++-dev

- name: compile and install
  become: true
  shell: "{{ item }}"
  args:
    chdir: /usr/local/src/cquery-{{ cquery_version }}
  with_items:
    # Build on Ubuntu 14.04
    # https://github.com/cquery-project/cquery/wiki/Build-%28Waf%29#ubuntu-1404
    - ./waf configure  # Download llvm
    - CXX="/usr/local/src/cquery-{{ cquery_version }}/build/clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-14.04/bin/clang++" CXXFLAGS="-stdlib=libc++" LDFLAGS="-lc++" ./waf configure --llvm-config="/usr/local/src/cquery-{{ cquery_version }}/build/clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-14.04/bin/llvm-config" --prefix="/usr/local/stow/cquery-{{ cquery_version }}"  # noqa 204
    - ./waf build
    - ./waf install

- name: stow
  become: true
  shell: stow -R cquery-{{ cquery_version }}
  args:
    chdir: /usr/local/stow
