---

- name: add apt key
  become: yes
  apt_key:
    url: https://apt.llvm.org/llvm-snapshot.gpg.key

- name: add apt repository
  become: yes
  apt_repository:
    repo: >-
      deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main
    filename: llvm
    state: present

- name: install package
  become: yes
  apt:
    name: clang-format
