---

vscode_common_settings_file_path: /home/vagrant/.config/Code/User/settings.json

vscode_plugins:
  # ----------------------------------------------------------------------------
  # Common
  # ----------------------------------------------------------------------------
  - streetsidesoftware.code-spell-checker
  - wraith13.wandbox-vscode
  #
  #
  # ----------------------------------------------------------------------------
  # C++
  # ----------------------------------------------------------------------------
  - ajshort.include-autocomplete
  - twxs.cmake
  #
  # maybe ms-vscode.cpptools works well, otherwise use following plugins
  # - mitaki28.vscode-clang
  # - xaver.clang-format
  # - austin.code-gnu-global // MEMO: Need gnu-global installation to use this.
  - ms-vscode.cpptools
  #
  # TODO: install cpplint and set path
  # - mine.cpplint
  #
  #
  # ----------------------------------------------------------------------------
  # CSV
  # ----------------------------------------------------------------------------
  - GrapeCity.gc-excelviewer
  - mechatroner.rainbow-csv
  #
  #
  # ----------------------------------------------------------------------------
  # Docker
  # ----------------------------------------------------------------------------
  - PeterJausovec.vscode-docker
  #
  #
  # ----------------------------------------------------------------------------
  # Git
  # ----------------------------------------------------------------------------
  - eamodio.gitlens
  #
  #
  # ----------------------------------------------------------------------------
  # Java
  # ----------------------------------------------------------------------------
  - redhat.java
  #
  #
  # ----------------------------------------------------------------------------
  # Markdown
  # ----------------------------------------------------------------------------
  - DavidAnson.vscode-markdownlint
  - shuworks.vscode-table-formatter
  #
  #
  # ----------------------------------------------------------------------------
  # Protocol buffers
  # ----------------------------------------------------------------------------
  - zxh404.vscode-proto3
  #
  #
  # ----------------------------------------------------------------------------
  # Python
  # ----------------------------------------------------------------------------
  - ms-python.python
  #
  #
  # ----------------------------------------------------------------------------
  # Restructured text
  # ----------------------------------------------------------------------------
  - lextudio.restructuredtext
  #
  #
  # ----------------------------------------------------------------------------
  # Vagrant
  # ----------------------------------------------------------------------------
  - marcostazi.vs-code-vagrantfile
  #
  #
  # ----------------------------------------------------------------------------
  # Xml
  # ----------------------------------------------------------------------------
  - DotJoshJohnson.xml
