---

- hosts: all
  roles:
    - cquery
    - ghex
    - git
    - git-flow
    - gitk
    - i3
    - lightdm-conf
    - moreutils
    - pandoc
    - rtags
    - samba
    - sysstat
    - thunar
    - vscode
    - xfce4-terminal
    - yamllint
