---

- hosts: all
  roles:
    - cpplint
    - cquery
    - firefox-esr
    - ghex
    - git-flow
    - git-ignore
    - gitk
    - i3
    - lightdm-conf
    - nsswitch
    - rtags
    - samba
    - thunar
    - vscode
    - xfce4-terminal
    - yamllint
