---
- name: install requirements
  become: yes
  pacman:
    name:
      - base-devel

- name: install packages
  aur:
    name: visual-studio-code-bin

- name: install plugins
  include_tasks: inner/install_plugin.yml
  with_items: "{{ vscode_plugins }}"
  loop_control:
    loop_var: vscode_plugin

- name: put user settings.json
  copy:
    src: settings.json
    dest: "/home/vagrant/.config/Code/User/settings.json"
    mode: 0664

- name: add locale.json
  copy:
    src: locale.json
    dest: "/home/vagrant/.config/Code/User/locale.json"
    mode: 0664
