---

- hosts: all
  roles:
    - distribution

# common roles (tested by molecule)
- hosts: all
  roles:
    - cplusplus
    - firefox
    - git
    - nkf
    - python
    - shellcheck
    - xmllint
    - zip

# common roles (not-tested by molecule)
- hosts: all
  roles:
    - inotify

- import_playbook: ubuntu-xenial.yml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "16.04"

- import_playbook: ubuntu-bionic.yml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "18.04"
