---

- hosts: all
  roles:
    - distribution
    - setup

# common roles (tested by molecule)
- hosts: all
  roles:
    - cplusplus
    - git
    - gui_applications
    - nkf
    - prompt
    - python
    - rust
    - shellcheck
    - vscode
    - xmllint
    - zip

# common roles (not-tested by molecule)
- hosts: all
  roles:
    - bash-completion
    - docker
    - font
    - i3
    - inotify
    - inputrc
    - localization
    - samba
    - swap
    - xdm
    - xfce4-terminal
