---

- name: setup
  hosts: all
  roles:
    - apt

- name: main
  hosts: all
  roles:
    - cpplint-xenial
    - docker-compose-xenial
    - git-config
    - i3-bionic
    - initrc
    - prompt
    - rtags-xenial
    - samba-xenial
    - swap
    - thunar
    - vscode
    - xdm
    - xfce4-terminal
    - yamllint
