---

- name: setup
  hosts: all
  roles:
    - apt

- name: main
  hosts: all
  roles:
    - docker-compose
    - i3-bionic
    - initrc
    - pipenv
    - prompt
    - vscode
    - xdm
    - xfce4-terminal
