---

- name: setup
  hosts: all
  roles:
    - apt

- name: main
  hosts: all
  roles:
    - bash-completion
    - clang-format
    - cpplint-xenial
    - docker-compose-xenial
    - font
    - ghex
    - git-config
    - gitk
    - i3-bionic
    - initrc
    - localization
    - meld
    - ninja-build
    - prompt
    - python
    - rtags-xenial
    - samba-xenial
    - swap
    - thunar
    - vscode
    - xdm
    - xfce4-terminal
    - yamllint
