---

- name: setup
  hosts: all
  roles:
    - apt

- name: main
  hosts: all
  roles:
    - docker-compose-xenial
    - i3-bionic
    - prompt
    - rtags-xenial
    - samba
    - swap
    - thunar
    - vscode
