---

- name: install requirements
  become: yes
  apt:
    name:
      - git

- name: install packages
  become: yes
  apt:
    name:
      - i3
      - i3blocks
      - sysstat  # required by i3blocks-contrib blocklet cpu_usage

- name: create directories to put config file
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /home/vagrant/.config/i3
    - /home/vagrant/.config/i3blocks

- name: add config file
  copy:
    src: i3wm-config
    dest: /home/vagrant/.config/i3/config
    mode: 0664

- name: add i3blocks config file
  copy:
    src: i3blocks.conf
    dest: /home/vagrant/.config/i3blocks/config
    mode: 0664

- name: checkout i3blocks-contrib git repository
  become: yes
  git:
    repo: https://github.com/vivien/i3blocks-contrib.git
    dest: /usr/local/src/i3blocks-contrib-{{ i3blocks_contrib_commit }}
    version: "{{ i3blocks_contrib_commit }}"

- name: create directory to put i3blocks-contrib blocklets
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /home/vagrant/.local/share/i3blocks/

- name: put i3blocks-contrib blocklet bandwidth
  file:
    src: /usr/local/src/i3blocks-contrib-{{ i3blocks_contrib_commit }}/bandwidth/bandwidth
    dest: /home/vagrant/.local/share/i3blocks/bandwidth
    state: link

- name: put i3blocks-contrib blocklet cpu_usage
  file:
    src: /usr/local/src/i3blocks-contrib-{{ i3blocks_contrib_commit }}/cpu_usage/cpu_usage
    dest: /home/vagrant/.local/share/i3blocks/cpu_usage
    state: link

- name: put i3blocks-contrib blocklet memory
  file:
    src: /usr/local/src/i3blocks-contrib-{{ i3blocks_contrib_commit }}/memory/memory
    dest: /home/vagrant/.local/share/i3blocks/memory
    state: link

- name: put i3blocks-contrib blocklet load_average
  file:
    src: /usr/local/src/i3blocks-contrib-{{ i3blocks_contrib_commit }}/load_average/load_average
    dest: /home/vagrant/.local/share/i3blocks/load_average
    state: link
