---

- name: install packages
  become: yes
  apt:
    name: i3

- name: add config file
  copy:
    src: config
    dest: /home/vagrant/.i3/
    mode: 0664

- name: remove CR code in config file
  replace:
    dest: /home/vagrant/.i3/config
    regexp: '\r'
    replace: ''

- name: add i3status config file
  copy:
    src: i3status.conf
    dest: /home/vagrant/.i3status.conf
    mode: 0664

- name: remove CR code in i3status config file
  replace:
    dest: /home/vagrant/.i3status.conf
    regexp: '\r'
    replace: ''
