---

- name: install dependencies
  become: yes
  apt:
    name:
      - clang
      - libclang-dev
      - libcppunit-dev

- name: download and unarchive source code
  become: yes
  unarchive:
    src: "https://github.com/Andersbakken/rtags/releases/download/v{{ rtags_version }}/rtags-{{ rtags_version }}.tar.gz"
    dest: "/usr/local/src"
    remote_src: yes

- name: create working directory to build
  become: yes
  file:
    path: "/usr/local/src/rtags-{{ rtags_version }}/build"
    state: directory

- name: compile and install
  become: yes
  shell: "{{ item }}"
  args:
    chdir: /usr/local/src/rtags-{{ rtags_version }}/build
  with_items:
    - cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local/stow/rtags-{{ rtags_version }} -DRTAGS_NO_ELISP_FILES=1  # noqa 204
    - make
    - make install

- name: stow package
  become: yes
  args:
    chdir: /usr/local/stow
  shell: |-
    ls | grep 'rtags-*' | xargs -n1 stow -D
    stow -R rtags-{{ rtags_version }}

- name: create directory to put systemd config files
  file:
    path: ~/.config/systemd/user
    state: directory

- name: add systemd file rdm.socket
  copy:
    src: rdm.socket
    dest: ~/.config/systemd/user/rdm.socket
    mode: 0664

- name: add systemd file rdm.service
  copy:
    src: rdm.service
    dest: ~/.config/systemd/user/rdm.service
    mode: 0664

- name: enable systemd user unit
  systemd:
    name: rdm.socket
    scope: user
    enabled: yes

- name: start systemd user unit
  systemd:
    name: rdm.socket
    scope: user
    state: started
