---

- name: setup
  hosts: all
  roles:
    - apt

- name: main
  hosts: all
  roles:
    - bash-completion
    - docker-compose
    - firefox
    - font
    - i3-bionic
    - localization
    - pipenv
    - prompt
    - vscode
    - xdm
    - xfce4-terminal
