---

- name: setup
  hosts: all
  roles:
    - apt

- name: main
  hosts: all
  roles:
    - bash-completion
    - cquery-xenial
    - docker-compose-xenial
    - firefox
    - font
    - i3-bionic
    - initrc
    - localization
    - meld
    - ninja-build
    - nkf
    # - pipenv
    - prompt
    - vscode
    - xdm
    - xfce4-terminal
